### ISSUE TITLE
BHTTP: support truncation for received known-length requests

### ISSUE THREAD

**Issue by v-burylov-flo** [cloudflare/privacy-gateway-server-go#42]
BHTTP requests with truncated empty content and trailer field sections are not processed as expected according to BHTTP specs.

_Example_:

 Request with truncated empty content and trailer field section (doesn't work):
`0004504f5354056874747073186170692e73746167696e672e6f776865616c74682e636f6d1c2f63616c6c2f76312f75736572732f6d652f616e6f6e796d697a6564409c06416363657074106170706c69636174696f6e2f6a736f6e09582d4170692d4b65792466336161646639652d616562632d343061322d383265322d38616362643439346665326611582d4170706c69636174696f6e2d4b65792435646133323532612d323931392d343033622d393035342d3538643965653430656435620c436f6e74656e742d54797065106170706c69636174696f6e2f6a736f6e`

Same request with zero-length empty content and trailer field section (works):
`0004504f5354056874747073186170692e73746167696e672e6f776865616c74682e636f6d1c2f63616c6c2f76312f75736572732f6d652f616e6f6e796d697a6564409c06416363657074106170706c69636174696f6e2f6a736f6e09582d4170692d4b65792466336161646639652d616562632d343061322d383265322d38616362643439346665326611582d4170706c69636174696f6e2d4b65792435646133323532612d323931392d343033622d393035342d3538643965653430656435620c436f6e74656e742d54797065106170706c69636174696f6e2f6a736f6e0000`

**Comment by chris-wood** [comment]
@v-burylov-flo Sorry for the delay in getting back to you on this issue. I'm not sure the truncated request example is correct. Per the spec:

> If the trailers of a message are empty, they MAY be omitted by the encoder in place of adding a length field equal to zero. An encoder MAY omit empty content in the same way if the trailers are also empty. A message that is truncated at any other point is invalid; see [Section 4](https://datatracker.ietf.org/doc/html/rfc9292#invalid).[¶](https://datatracker.ietf.org/doc/html/rfc9292#section-3.8-2)

In particular, this says that truncation does not mean simply dropping the bytes altogether, but instead advocates for replacing them with a single zero byte (a length field equal to zero).

The example provided seems to truncate literally by dropping these length fields altogether, which seems invalid. Could you please let me know if I'm misunderstanding something here?

**Comment by chris-wood** [comment]
I added some tests that demonstrate my understanding of the spec [in this PR](https://github.com/chris-wood/ohttp-go/pull/21). Please have a look!

**Comment by v-burylov-flo** [comment]
@chris-wood, thank you for the answer. I got confused about what 'in place of adding a length field equal to zero' means.

At first, I interpreted it as '_when trailers are empty, they may be omitted, only length field equal to zero is necessary_.' But the responses that the gateway generates do not conform to that - if trailers and content of the response are empty, there are no zero-length fields, and the message ends there. And my decoding of such responses failed, as it expected the length field equal to zero but got EOF.

Then I thought - maybe I should read the spec as '_when trailers are empty, they may be omitted **instead** of adding a length field equal to zero_.' If I treat responses from the gateway like this, I no longer have issues with them. But then I get a problem with my requests because the gateway expects a length field equal to zero in them. That is why I submitted this issue.

So, if my original understanding was correct, and a length field equal to zero is necessary, then the issue is not with how the gateway processes truncated requests but with how it produces truncated responses. Can you look into that, please?

**Comment by chris-wood** [comment]
@v-burylov-flo do you have a way to reproduce such a response from the gateway? A quick skim of the response encoding code in the ohttp-go library suggests that content and trailer fields are always added, even if their length is zero.
