### ISSUE TITLE
Redirecting to a target on loopback

### ISSUE THREAD

**Issue by tgeoghegan** [cloudflare/privacy-gateway-server-go#56]
I'm interested in using `privacy-gateway-server-go` in a setup where it and the OHTTP target are on the same loopback (`localhost`) interface (concretely, they're both in the same Kubernetes pod, but we don't need to get into Kubernetes details to discuss this issue). I want the gateway to be able to forward decapsulated requests to the target without going back out to the internet. The problem is that `privacy-gateway-server-go` uses the encapsulated request's control data to decide what scheme and authority to forward the request to, but that will be the publicly routable DNS name for the target, not its port on the loopback interface.

To make this concrete: let's imagine that I have the OHTTP gateway exposed to the internet at `https://example.com/gateway` and the target exposed at `https://example.com/target`. Further, let's suppose that the target is visible to the gateway at `localhost:80`.

If a client wants to hit some API on the target, it would construct and encapsulate an HTTP request:

```http
POST /some-cool-api HTTP/1.1

some content
```

...and then POST that to `https://example.com/gateway`. This won't work, because `privacy-gateway-server-go` will try to forward the request to `https:///some-cool-api`. OK, let's put the entire target URL in the encapsulated request:

```http
POST https://example.org/target/some-cool-api HTTP/1.1

some content
```

This _does_ work, but not the way I want: `privacy-gateway-server-go` will go do a DNS lookup for `example.org` and connect to the target over the internet, but I want to do this over loopback and without TLS. This encapsulated request works (note http and not http**s**):

```http
POST http://localhost:80/target/some-cool-api HTTP/1.1

some content
```

...but this solution isn't great, because now the client needs to know details of the private network namespace that the target and gateway are on. Similar things can be achieved with a `Host` header instead of putting the authority in the first line of the HTTP request, but spelling out the entire URL makes it easier to control the scheme.

I think what I would like is a configuration option on `privacy-gateway-server-go` that allows operators to provide a map of origins to origins used to rewrite requests forwarded to targets. So in the scenario above, I could run the gateway with:

```json
{ "https://example.org": "http://localhost:80" }
```

And then when the gateway encounters the key in an encapsulated request, it forwards the request to the value (preserving the request path). If this solution sounds good to the maintainers, then I'd be happy to work on a PR for this.

**Comment by cjpatton** [comment]
Hey Tim, not to bikeshed on threat models, I'm just curious how to read the PR: is this set up intended for testing?

**Comment by tgeoghegan** [comment]
No, I want to do this in production (unless you point out to me that it's insecure or somehow breaks OHTTP). The use case is that I'm running the gateway and the target as two containers in the same Kubernetes pod. In Kubernetes, every container in a pod gets spawned into the same Linux network namespace, so they share a loopback interface and can communicate efficiently over it (certainly much cheaper than routing back over the internet). There's a popular Kubernetes pattern called a ["sidecar container"](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) that uses this feature to do things like run a reverse proxy that terminates authentication next to the application. I want to do something similar with the OHTTP gateway.
