### ISSUE TITLE
Structured JSON logs

### ISSUE THREAD

**Issue by tgeoghegan** [cloudflare/privacy-gateway-server-go#61]
Logging is currently done via `log.Printf`. This is fine, but integrates poorly with log indexing products like Splunk or Google Cloud Logging. Multi-line messages (such as the config object that `privacy-gateway-server-go` logs at startup) appear as multiple distinct events. Events have no severity or level on them, so we cannot configure log level and the indexer must make an assumption about how to store events (Google Cloud Logging, for instance, labels everything as `level = ERROR`, which is annoying). And it's hard to search for events because the log statements aren't structured.

What I'd like to do is add an option for structured JSON logging. Then, instead of simply logging the string:

```
2024/05/20 15:38:31 GET Handling /health
```

You would get:

```json
{
  "timestamp":  "2024-05-20T15:38:31Z",
  "message": "GET Handling /health",
  "level": "info"
}
```

And we'd also add an option for configuring the log level, allowing operators to filter out less interesting events. For example, logging every time a health check succeeds is wasteful, so I think we'd kick that up to debug.

If the maintainers are on board with this idea, I'd be happy to work on it. But I'd appreciate guidance on what Go logging package your team prefers. [`rs/zerolog`](https://github.com/rs/zerolog) and [`uber-go/zap`](https://github.com/uber-go/zap) are popular. Does Cloudflare have a preferred logging package?

**Comment by tgeoghegan** [comment]
I've just learned that Go has a built in structured logging package [`slog`](https://go.dev/blog/slog) as of 1.21, so I think that's what I'd use.

**Comment by cjpatton** [comment]
Hey @tgeoghegan, since this is potentially a breaking change for monitoring, I'm double checking that noone has a deployment internally for this would matter. I strongly suspect we'll be able to land this.

**Comment by tgeoghegan** [comment]
Backward compatibility is a good point. I think we'd be able to default to the existing log format and add an opt-in for structured logs.

**Comment by cjpatton** [comment]
Would that be a lot more work?

**Comment by cjpatton** [comment]
I've confirmed that you're good to make this breaking change. Don't worry about backwards compatibility.

**Comment by tgeoghegan** [comment]
Worst case you'd have to put `log.Printf`s alongside the `slog` statements. But in any case, moving to structured-only seems wiser and easier, if nobody is concerned about breaking some carefully constructed `grep`.

**Comment by tgeoghegan** [comment]
Related question: the stdlib `slog` package is available in Go 1.21 and up. `go.mod` currently uses 1.17, and the Dockerfile is using 1.20. How do you feel about moving this to Go 1.21? If that's a no-go (which would be understandable), what logging package would you prefer?

**Comment by bwesterb** [comment]
I think we're good upgrading to Go 1.21 — WDYT @cjpatton ?

**Comment by cjpatton** [comment]
I have no objection to bumping Go. Note that we don't have any internal deployments of this code in particular (the Privacy Edge team has a different implementation that they deploy).
